### ISSUE TITLE
Error in Running API Key Cell

### ISSUE THREAD

**Issue by muhammadatifaltaf** [textcortex/hemingwai#2]
Hi!
  When I entered the API key and run the cell then it gives me an error:
**ERROR:root:Ops, error {'status': 'fail', 'message': 'An error happened while processing your request', 'error': 500}
None**
Please guide or help to solve it! Thanks!
![image](https://user-images.githubusercontent.com/74616058/174267734-787c54b2-681d-46c0-9d2e-c56f348dd3bc.png)

**Comment by cderinbogaz** [comment]
Hi @muhammadatifaltaf 

Thanks for creating an issue. We looked into it and realised this was happening because of some updates on our backend. We have updated the textcortex python package to v2.0.0 which solves this issue.
Please update your package and give it another go.
Thanks!
